/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "Editor.h"

static ORBitSmallSkeleton get_skel_small_GNOME_GtkHTML_Editor_Listener(POA_GNOME_GtkHTML_Editor_Listener *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case 'e':
if(strcmp((opname + 1), "vent")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Listener_epv->event;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Listener__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Listener_event;
break;
case 'q':
if(strcmp((opname + 1), "ueryInterface")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->queryInterface;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [2];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_queryInterface;
break;
case 'r':
if(strcmp((opname + 1), "ef")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->ref;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_ref;
break;
case 'u':
if(strcmp((opname + 1), "nref")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->unref;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [1];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_unref;
break;
default: break; 
}
return NULL;
}

void POA_GNOME_GtkHTML_Editor_Listener__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (ORBit_small_impl_finder)&get_skel_small_GNOME_GtkHTML_Editor_Listener, "IDL:GNOME/GtkHTML/Editor/Listener:1.0", &GNOME_GtkHTML_Editor_Listener__classid, NULL, &GNOME_GtkHTML_Editor_Listener__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
  POA_Bonobo_Unknown__init(servant, env);
   ORBit_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_GNOME_GtkHTML_Editor_Listener__fini,
   ORBIT_VEPV_OFFSET (POA_GNOME_GtkHTML_Editor_Listener__vepv, GNOME_GtkHTML_Editor_Listener_epv),
(CORBA_unsigned_long) Bonobo_Unknown__classid,
ORBIT_VEPV_OFFSET (POA_GNOME_GtkHTML_Editor_Listener__vepv, Bonobo_Unknown_epv),
   (CORBA_unsigned_long) 0);}

void POA_GNOME_GtkHTML_Editor_Listener__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  POA_Bonobo_Unknown__fini(servant, env);
  PortableServer_ServantBase__fini(servant, env);
}

static ORBitSmallSkeleton get_skel_small_GNOME_GtkHTML_Editor_Engine(POA_GNOME_GtkHTML_Editor_Engine *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case '_':
switch(opname[1]) {
case 'g':
if(strcmp((opname + 2), "et_listener")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->_get_listener;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine__get_listener;
break;
case 's':
if(strcmp((opname + 2), "et_listener")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->_set_listener;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [1];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine__set_listener;
break;
default: break; 
}
break;
case 'd':
if(strcmp((opname + 1), "ropUndo")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->dropUndo;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [15];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_dropUndo;
break;
case 'f':
if(strcmp((opname + 1), "reeze")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->freeze;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [10];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_freeze;
break;
case 'g':
if(strcmp((opname + 1), "etParagraphData")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->getParagraphData;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [3];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_getParagraphData;
break;
case 'h':
if(strcmp((opname + 1), "asUndo")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->hasUndo;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [16];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_hasUndo;
break;
case 'i':
switch(opname[1]) {
case 'g':
if(strcmp((opname + 2), "noreWord")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->ignoreWord;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [14];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_ignoreWord;
break;
case 'n':
if(strcmp((opname + 2), "sertHTML")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->insertHTML;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [9];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_insertHTML;
break;
case 's':
switch(opname[2]) {
case 'P':
switch(opname[3]) {
case 'a':
if(strcmp((opname + 4), "ragraphEmpty")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->isParagraphEmpty;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [7];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_isParagraphEmpty;
break;
case 'r':
if(strcmp((opname + 4), "eviousParagraphEmpty")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->isPreviousParagraphEmpty;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [8];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_isPreviousParagraphEmpty;
break;
default: break; 
}
break;
default: break; 
}
break;
default: break; 
}
break;
case 'q':
if(strcmp((opname + 1), "ueryInterface")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->queryInterface;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [2];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_queryInterface;
break;
case 'r':
switch(opname[1]) {
case 'e':
if(strcmp((opname + 2), "f")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->ref;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_ref;
break;
case 'u':
if(strcmp((opname + 2), "nCommand")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->runCommand;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [2];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_runCommand;
break;
default: break; 
}
break;
case 's':
switch(opname[1]) {
case 'e':
switch(opname[2]) {
case 'a':
if(strcmp((opname + 3), "rchByData")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->searchByData;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [6];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_searchByData;
break;
case 't':
switch(opname[3]) {
case 'O':
if(strcmp((opname + 4), "bjectDataByType")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->setObjectDataByType;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [5];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_setObjectDataByType;
break;
case 'P':
if(strcmp((opname + 4), "aragraphData")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->setParagraphData;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [4];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_setParagraphData;
break;
default: break; 
}
break;
default: break; 
}
break;
default: break; 
}
break;
case 't':
if(strcmp((opname + 1), "haw")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->thaw;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [11];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_thaw;
break;
case 'u':
switch(opname[1]) {
case 'n':
switch(opname[2]) {
case 'd':
switch(opname[3]) {
case 'o':
switch(opname[4]) {
case 'B':
if(strcmp((opname + 5), "egin")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->undoBegin;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [12];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_undoBegin;
break;
case 'E':
if(strcmp((opname + 5), "nd")) break;
*impl = (gpointer)servant->vepv->GNOME_GtkHTML_Editor_Engine_epv->undoEnd;
{ORBit_IInterface *volatile _t_=&GNOME_GtkHTML_Editor_Engine__iinterface;*m_data = (gpointer)&_t_->methods._buffer [13];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_undoEnd;
break;
default: break; 
}
break;
default: break; 
}
break;
case 'r':
if(strcmp((opname + 3), "ef")) break;
*impl = (gpointer)servant->vepv->Bonobo_Unknown_epv->unref;
{ORBit_IInterface *volatile _t_=&Bonobo_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [1];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_Bonobo_Unknown_unref;
break;
default: break; 
}
break;
default: break; 
}
break;
default: break; 
}
return NULL;
}

void POA_GNOME_GtkHTML_Editor_Engine__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (ORBit_small_impl_finder)&get_skel_small_GNOME_GtkHTML_Editor_Engine, "IDL:GNOME/GtkHTML/Editor/Engine:1.0", &GNOME_GtkHTML_Editor_Engine__classid, NULL, &GNOME_GtkHTML_Editor_Engine__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
  POA_Bonobo_Unknown__init(servant, env);
   ORBit_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_GNOME_GtkHTML_Editor_Engine__fini,
   ORBIT_VEPV_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__vepv, GNOME_GtkHTML_Editor_Engine_epv),
(CORBA_unsigned_long) Bonobo_Unknown__classid,
ORBIT_VEPV_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__vepv, Bonobo_Unknown_epv),
   (CORBA_unsigned_long) 0);}

void POA_GNOME_GtkHTML_Editor_Engine__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  POA_Bonobo_Unknown__fini(servant, env);
  PortableServer_ServantBase__fini(servant, env);
}

