/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "Editor.h"

CORBA_any* GNOME_GtkHTML_Editor_Listener_event(GNOME_GtkHTML_Editor_Listener _obj, const CORBA_char * name, const CORBA_any* arg, CORBA_Environment *ev){
CORBA_any* _ORBIT_retval;
gpointer _args[2];
_args[0] = (gpointer)&name;
_args[1] = (gpointer)arg;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Listener__iinterface.methods, 0, &_ORBIT_retval, _args, NULL, ev, GNOME_GtkHTML_Editor_Listener__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Listener__epv, event),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Listener_event);

return _ORBIT_retval;
}
GNOME_GtkHTML_Editor_Listener GNOME_GtkHTML_Editor_Engine__get_listener(GNOME_GtkHTML_Editor_Engine _obj, CORBA_Environment *ev){
GNOME_GtkHTML_Editor_Listener _ORBIT_retval;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 0, &_ORBIT_retval, NULL, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, _get_listener),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine__get_listener);

return _ORBIT_retval;
}
void GNOME_GtkHTML_Editor_Engine__set_listener(GNOME_GtkHTML_Editor_Engine _obj, const GNOME_GtkHTML_Editor_Listener value, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&value;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 1, NULL, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, _set_listener),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine__set_listener);

}
CORBA_boolean GNOME_GtkHTML_Editor_Engine_runCommand(GNOME_GtkHTML_Editor_Engine _obj, const CORBA_char * command, CORBA_Environment *ev){
CORBA_boolean _ORBIT_retval;
gpointer _args[1];
_args[0] = (gpointer)&command;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 2, &_ORBIT_retval, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, runCommand),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_runCommand);

return _ORBIT_retval;
}
CORBA_string GNOME_GtkHTML_Editor_Engine_getParagraphData(GNOME_GtkHTML_Editor_Engine _obj, const CORBA_char * key, CORBA_Environment *ev){
CORBA_string _ORBIT_retval;
gpointer _args[1];
_args[0] = (gpointer)&key;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 3, &_ORBIT_retval, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, getParagraphData),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_getParagraphData);

return _ORBIT_retval;
}
void GNOME_GtkHTML_Editor_Engine_setParagraphData(GNOME_GtkHTML_Editor_Engine _obj, const CORBA_char * key, const CORBA_char * value, CORBA_Environment *ev){
gpointer _args[2];
_args[0] = (gpointer)&key;
_args[1] = (gpointer)&value;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 4, NULL, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, setParagraphData),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_setParagraphData);

}
void GNOME_GtkHTML_Editor_Engine_setObjectDataByType(GNOME_GtkHTML_Editor_Engine _obj, const CORBA_char * type_name, const CORBA_char * key, const CORBA_char * data, CORBA_Environment *ev){
gpointer _args[3];
_args[0] = (gpointer)&type_name;
_args[1] = (gpointer)&key;
_args[2] = (gpointer)&data;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 5, NULL, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, setObjectDataByType),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_setObjectDataByType);

}
CORBA_boolean GNOME_GtkHTML_Editor_Engine_searchByData(GNOME_GtkHTML_Editor_Engine _obj, const CORBA_long level, const CORBA_char * klass, const CORBA_char * key, const CORBA_char * value, CORBA_Environment *ev){
CORBA_boolean _ORBIT_retval;
gpointer _args[4];
_args[0] = (gpointer)&level;
_args[1] = (gpointer)&klass;
_args[2] = (gpointer)&key;
_args[3] = (gpointer)&value;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 6, &_ORBIT_retval, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, searchByData),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_searchByData);

return _ORBIT_retval;
}
CORBA_boolean GNOME_GtkHTML_Editor_Engine_isParagraphEmpty(GNOME_GtkHTML_Editor_Engine _obj, CORBA_Environment *ev){
CORBA_boolean _ORBIT_retval;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 7, &_ORBIT_retval, NULL, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, isParagraphEmpty),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_isParagraphEmpty);

return _ORBIT_retval;
}
CORBA_boolean GNOME_GtkHTML_Editor_Engine_isPreviousParagraphEmpty(GNOME_GtkHTML_Editor_Engine _obj, CORBA_Environment *ev){
CORBA_boolean _ORBIT_retval;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 8, &_ORBIT_retval, NULL, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, isPreviousParagraphEmpty),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_isPreviousParagraphEmpty);

return _ORBIT_retval;
}
void GNOME_GtkHTML_Editor_Engine_insertHTML(GNOME_GtkHTML_Editor_Engine _obj, const CORBA_char * html, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&html;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 9, NULL, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, insertHTML),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_insertHTML);

}
void GNOME_GtkHTML_Editor_Engine_freeze(GNOME_GtkHTML_Editor_Engine _obj, CORBA_Environment *ev){
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 10, NULL, NULL, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, freeze),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_freeze);

}
void GNOME_GtkHTML_Editor_Engine_thaw(GNOME_GtkHTML_Editor_Engine _obj, CORBA_Environment *ev){
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 11, NULL, NULL, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, thaw),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_thaw);

}
void GNOME_GtkHTML_Editor_Engine_undoBegin(GNOME_GtkHTML_Editor_Engine _obj, const CORBA_char * undo_name, const CORBA_char * redo_name, CORBA_Environment *ev){
gpointer _args[2];
_args[0] = (gpointer)&undo_name;
_args[1] = (gpointer)&redo_name;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 12, NULL, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, undoBegin),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_undoBegin);

}
void GNOME_GtkHTML_Editor_Engine_undoEnd(GNOME_GtkHTML_Editor_Engine _obj, CORBA_Environment *ev){
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 13, NULL, NULL, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, undoEnd),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_undoEnd);

}
void GNOME_GtkHTML_Editor_Engine_ignoreWord(GNOME_GtkHTML_Editor_Engine _obj, const CORBA_char * word, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&word;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 14, NULL, _args, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, ignoreWord),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_ignoreWord);

}
void GNOME_GtkHTML_Editor_Engine_dropUndo(GNOME_GtkHTML_Editor_Engine _obj, CORBA_Environment *ev){
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 15, NULL, NULL, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, dropUndo),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_dropUndo);

}
CORBA_boolean GNOME_GtkHTML_Editor_Engine_hasUndo(GNOME_GtkHTML_Editor_Engine _obj, CORBA_Environment *ev){
CORBA_boolean _ORBIT_retval;
ORBit_c_stub_invoke (_obj, &GNOME_GtkHTML_Editor_Engine__iinterface.methods, 16, &_ORBIT_retval, NULL, NULL, ev, GNOME_GtkHTML_Editor_Engine__classid, G_STRUCT_OFFSET (POA_GNOME_GtkHTML_Editor_Engine__epv, hasUndo),
(ORBitSmallSkeleton) _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_hasUndo);

return _ORBIT_retval;
}
