/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#define ORBIT_IDL_C_COMMON
#define Editor_COMMON
#include "Editor.h"

static const CORBA_unsigned_long ORBit_zero_int = 0;

#ifndef ORBIT_IDL_C_IMODULE_Editor
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Listener_event(POA_GNOME_GtkHTML_Editor_Listener             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_any* (*_impl_event)(PortableServer_Servant _servant, const CORBA_char * name, const CORBA_any* arg, CORBA_Environment *ev)) {
*(CORBA_any* *)_o_retval = _impl_event (_o_servant, *(const CORBA_char * *)_o_args[0], (const CORBA_any*)_o_args[1], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine__get_listener(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
GNOME_GtkHTML_Editor_Listener (*_impl__get_listener)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
*(GNOME_GtkHTML_Editor_Listener *)_o_retval = _impl__get_listener (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine__set_listener(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl__set_listener)(PortableServer_Servant _servant, const GNOME_GtkHTML_Editor_Listener value, CORBA_Environment *ev)) {
_impl__set_listener (_o_servant, *(const GNOME_GtkHTML_Editor_Listener *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_runCommand(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_boolean (*_impl_runCommand)(PortableServer_Servant _servant, const CORBA_char * command, CORBA_Environment *ev)) {
*(CORBA_boolean *)_o_retval = _impl_runCommand (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_getParagraphData(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_string (*_impl_getParagraphData)(PortableServer_Servant _servant, const CORBA_char * key, CORBA_Environment *ev)) {
*(CORBA_string *)_o_retval = _impl_getParagraphData (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_setParagraphData(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_setParagraphData)(PortableServer_Servant _servant, const CORBA_char * key, const CORBA_char * value, CORBA_Environment *ev)) {
_impl_setParagraphData (_o_servant, *(const CORBA_char * *)_o_args[0], *(const CORBA_char * *)_o_args[1], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_setObjectDataByType(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_setObjectDataByType)(PortableServer_Servant _servant, const CORBA_char * type_name, const CORBA_char * key, const CORBA_char * data, CORBA_Environment *ev)) {
_impl_setObjectDataByType (_o_servant, *(const CORBA_char * *)_o_args[0], *(const CORBA_char * *)_o_args[1], *(const CORBA_char * *)_o_args[2], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_searchByData(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_boolean (*_impl_searchByData)(PortableServer_Servant _servant, const CORBA_long level, const CORBA_char * klass, const CORBA_char * key, const CORBA_char * value, CORBA_Environment *ev)) {
*(CORBA_boolean *)_o_retval = _impl_searchByData (_o_servant, *(const CORBA_long *)_o_args[0], *(const CORBA_char * *)_o_args[1], *(const CORBA_char * *)_o_args[2], *(const CORBA_char * *)_o_args[3], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_isParagraphEmpty(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_boolean (*_impl_isParagraphEmpty)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
*(CORBA_boolean *)_o_retval = _impl_isParagraphEmpty (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_isPreviousParagraphEmpty(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_boolean (*_impl_isPreviousParagraphEmpty)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
*(CORBA_boolean *)_o_retval = _impl_isPreviousParagraphEmpty (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_insertHTML(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_insertHTML)(PortableServer_Servant _servant, const CORBA_char * html, CORBA_Environment *ev)) {
_impl_insertHTML (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_freeze(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_freeze)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
_impl_freeze (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_thaw(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_thaw)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
_impl_thaw (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_undoBegin(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_undoBegin)(PortableServer_Servant _servant, const CORBA_char * undo_name, const CORBA_char * redo_name, CORBA_Environment *ev)) {
_impl_undoBegin (_o_servant, *(const CORBA_char * *)_o_args[0], *(const CORBA_char * *)_o_args[1], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_undoEnd(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_undoEnd)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
_impl_undoEnd (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_ignoreWord(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_ignoreWord)(PortableServer_Servant _servant, const CORBA_char * word, CORBA_Environment *ev)) {
_impl_ignoreWord (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_dropUndo(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_dropUndo)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
_impl_dropUndo (_o_servant, _o_ev);
}
void _ORBIT_skel_small_GNOME_GtkHTML_Editor_Engine_hasUndo(POA_GNOME_GtkHTML_Editor_Engine             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
CORBA_boolean (*_impl_hasUndo)(PortableServer_Servant _servant, CORBA_Environment *ev)) {
*(CORBA_boolean *)_o_retval = _impl_hasUndo (_o_servant, _o_ev);
}

#endif
#if ( (TC_IMPL_TC_GNOME_GtkHTML_Editor_Listener_0 == 'E') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Listener_1 == 'd') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Listener_2 == 'i') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Listener_3 == 't') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Listener_4 == 'o') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Listener_5 == 'r') \
) && !defined(TC_DEF_TC_GNOME_GtkHTML_Editor_Listener)
#define TC_DEF_TC_GNOME_GtkHTML_Editor_Listener 1
#ifdef ORBIT_IDL_C_IMODULE_Editor
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_GNOME_GtkHTML_Editor_Listener_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_objref,
0,
0,
ORBIT_ALIGNOF_CORBA_POINTER,
0,
0
,
NULL,
CORBA_OBJECT_NIL,
(char *)"Listener",
(char *)"IDL:GNOME/GtkHTML/Editor/Listener:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_GtkHTML_Editor_Engine_0 == 'E') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Engine_1 == 'd') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Engine_2 == 'i') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Engine_3 == 't') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Engine_4 == 'o') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_Engine_5 == 'r') \
) && !defined(TC_DEF_TC_GNOME_GtkHTML_Editor_Engine)
#define TC_DEF_TC_GNOME_GtkHTML_Editor_Engine 1
#ifdef ORBIT_IDL_C_IMODULE_Editor
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_GNOME_GtkHTML_Editor_Engine_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_objref,
0,
0,
ORBIT_ALIGNOF_CORBA_POINTER,
0,
0
,
NULL,
CORBA_OBJECT_NIL,
(char *)"Engine",
(char *)"IDL:GNOME/GtkHTML/Editor/Engine:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif
#if ( (TC_IMPL_TC_GNOME_GtkHTML_Editor_URLRequestEvent_0 == 'E') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_URLRequestEvent_1 == 'd') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_URLRequestEvent_2 == 'i') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_URLRequestEvent_3 == 't') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_URLRequestEvent_4 == 'o') \
&& (TC_IMPL_TC_GNOME_GtkHTML_Editor_URLRequestEvent_5 == 'r') \
) && !defined(TC_DEF_TC_GNOME_GtkHTML_Editor_URLRequestEvent)
#define TC_DEF_TC_GNOME_GtkHTML_Editor_URLRequestEvent 1
static const char *anon_subnames_array6[] = {"url", "stream"};
static ORBIT2_MAYBE_CONST CORBA_TypeCode anon_subtypes_array7[] = {(CORBA_TypeCode)&TC_CORBA_string_struct, (CORBA_TypeCode)&TC_Bonobo_Stream_struct};
#ifdef ORBIT_IDL_C_IMODULE_Editor
static
#endif
ORBIT2_MAYBE_CONST struct CORBA_TypeCode_struct TC_GNOME_GtkHTML_Editor_URLRequestEvent_struct = {
{&ORBit_TypeCode_epv, ORBIT_REFCOUNT_STATIC},
CORBA_tk_struct,
0,
0,
ORBIT_ALIGNOF_CORBA_POINTER,
0,
2
,
(CORBA_TypeCode *)anon_subtypes_array7,
CORBA_OBJECT_NIL,
(char *)"URLRequestEvent",
(char *)"IDL:GNOME/GtkHTML/Editor/URLRequestEvent:1.0",
(char **)anon_subnames_array6,
NULL,
-1,
0,
0, 0
};
#endif

#ifndef ORBIT_IDL_C_IMODULE_Editor
CORBA_unsigned_long GNOME_GtkHTML_Editor_Listener__classid = 0;
#endif

#ifndef ORBIT_IDL_C_IMODULE_Editor
CORBA_unsigned_long GNOME_GtkHTML_Editor_Engine__classid = 0;
#endif

/* Interface type data */

static ORBit_IArg GNOME_GtkHTML_Editor_Listener_event__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"name" },
	{ TC_CORBA_any,  ORBit_I_ARG_IN , (char *)"arg" }
};

#ifdef ORBIT_IDL_C_IMODULE_Editor
static
#endif
ORBit_IMethod GNOME_GtkHTML_Editor_Listener__imethods [] = {
	{
		{ 2, 2, GNOME_GtkHTML_Editor_Listener_event__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_any, (char *)"event", 5,
		0
}
};

static CORBA_string GNOME_GtkHTML_Editor_Listener__base_itypes[] = {
(char *)"IDL:Bonobo/Unknown:1.0",
(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_Editor
static
#endif
ORBit_IInterface GNOME_GtkHTML_Editor_Listener__iinterface = {
TC_GNOME_GtkHTML_Editor_Listener,{1, 1, GNOME_GtkHTML_Editor_Listener__imethods, FALSE},
{2, 2, GNOME_GtkHTML_Editor_Listener__base_itypes, FALSE}
};

static ORBit_IArg GNOME_GtkHTML_Editor_Engine__set_listener__arginfo [] = {
	{ TC_GNOME_GtkHTML_Editor_Listener,  ORBit_I_ARG_IN , (char *)"value" }
};
static ORBit_IArg GNOME_GtkHTML_Editor_Engine_runCommand__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"command" }
};
static ORBit_IArg GNOME_GtkHTML_Editor_Engine_getParagraphData__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"key" }
};
static ORBit_IArg GNOME_GtkHTML_Editor_Engine_setParagraphData__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"key" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"value" }
};
static ORBit_IArg GNOME_GtkHTML_Editor_Engine_setObjectDataByType__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"type_name" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"key" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"data" }
};
static ORBit_IArg GNOME_GtkHTML_Editor_Engine_searchByData__arginfo [] = {
	{ TC_CORBA_long,  ORBit_I_ARG_IN | ORBit_I_COMMON_FIXED_SIZE, (char *)"level" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"klass" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"key" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"value" }
};
static ORBit_IArg GNOME_GtkHTML_Editor_Engine_insertHTML__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"html" }
};
static ORBit_IArg GNOME_GtkHTML_Editor_Engine_undoBegin__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"undo_name" },
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"redo_name" }
};
static ORBit_IArg GNOME_GtkHTML_Editor_Engine_ignoreWord__arginfo [] = {
	{ TC_CORBA_string,  ORBit_I_ARG_IN , (char *)"word" }
};

#ifdef ORBIT_IDL_C_IMODULE_Editor
static
#endif
ORBit_IMethod GNOME_GtkHTML_Editor_Engine__imethods [] = {
	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_GNOME_GtkHTML_Editor_Listener, (char *)"_get_listener", 13,
		0
}
, 	{
		{ 1, 1, GNOME_GtkHTML_Editor_Engine__set_listener__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"_set_listener", 13,
		0
}
, 	{
		{ 1, 1, GNOME_GtkHTML_Editor_Engine_runCommand__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_boolean, (char *)"runCommand", 10,
		0| ORBit_I_COMMON_FIXED_SIZE
}
, 	{
		{ 1, 1, GNOME_GtkHTML_Editor_Engine_getParagraphData__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_string, (char *)"getParagraphData", 16,
		0
}
, 	{
		{ 2, 2, GNOME_GtkHTML_Editor_Engine_setParagraphData__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"setParagraphData", 16,
		0
}
, 	{
		{ 3, 3, GNOME_GtkHTML_Editor_Engine_setObjectDataByType__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"setObjectDataByType", 19,
		0
}
, 	{
		{ 4, 4, GNOME_GtkHTML_Editor_Engine_searchByData__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_boolean, (char *)"searchByData", 12,
		0| ORBit_I_COMMON_FIXED_SIZE
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_boolean, (char *)"isParagraphEmpty", 16,
		0| ORBit_I_COMMON_FIXED_SIZE
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_boolean, (char *)"isPreviousParagraphEmpty", 24,
		0| ORBit_I_COMMON_FIXED_SIZE
}
, 	{
		{ 1, 1, GNOME_GtkHTML_Editor_Engine_insertHTML__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"insertHTML", 10,
		0
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"freeze", 6,
		0
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"thaw", 4,
		0
}
, 	{
		{ 2, 2, GNOME_GtkHTML_Editor_Engine_undoBegin__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"undoBegin", 9,
		0
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"undoEnd", 7,
		0
}
, 	{
		{ 1, 1, GNOME_GtkHTML_Editor_Engine_ignoreWord__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"ignoreWord", 10,
		0
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"dropUndo", 8,
		0
}
, 	{
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
		TC_CORBA_boolean, (char *)"hasUndo", 7,
		0| ORBit_I_COMMON_FIXED_SIZE
}
};

static CORBA_string GNOME_GtkHTML_Editor_Engine__base_itypes[] = {
(char *)"IDL:Bonobo/Unknown:1.0",
(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef ORBIT_IDL_C_IMODULE_Editor
static
#endif
ORBit_IInterface GNOME_GtkHTML_Editor_Engine__iinterface = {
TC_GNOME_GtkHTML_Editor_Engine,{17, 17, GNOME_GtkHTML_Editor_Engine__imethods, FALSE},
{2, 2, GNOME_GtkHTML_Editor_Engine__base_itypes, FALSE}
};

