#!/usr/bin/env python
# encoding: utf8

def build(bld):

    source = 'slib-editor.c link_dialog.c' if bld.env['HAVE_EDITOR_IDL'] else \
        'bonobo-editor.c Editor-common.c Editor-skels.c Editor-stubs.c'

    bld.new_task_gen(
        features='cc cxx', # compile C with gcc, C++ with g++
        includes='. ../../ ../../src ../../src/editor %s' %
            bld.env['GECKO_INCLUDE'], # ../../ for config.h
        source=source,
        target='editor',
        #uselib='GLIB GNOMEUI SWORD GTKMOZEMBED GTKMOZEMBED_UNSTABLE GTKHTML GTKHTML_EDITOR'
        uselib= bld.env['ALL_LIBS'],
    )

