#!/usr/bin/env python
# encoding: utf8


source = 'link_dialog.c editor.c webkit_editor.c'

if bld.env['IS_WIN32']:
    x11_include = '../../win32/include'
else:
    x11_include = ' '

bld.new_task_gen(
    features='cc cxx', # compile C with gcc, C++ with g++
    includes='. ../.. ../../src ../../src/editor %s %s' % (bld.env['GECKO_INCLUDE'], x11_include), # ../../ for config.h
    source=source,
    target='editor',
    uselib= bld.env['ALL_LIBS'],
)

