#!/usr/bin/env python
# encoding: utf8

import os, os.path


def configure(conf):

    import Utils
    env = conf.env
    sub = Utils.subst_vars

    # bonobo editor
    if not env['HAVE_EDITOR_IDL']:
        # generade src files from IDL - must be run before compilation
        src_dir =os.getcwd()
        editor_dir = os.path.join(src_dir, 'src', 'editor')
            
        cmd = sub('${ORBIT_IDL} --output-dir=%s -I%s ${BONOBO_IDL_INCLUDES} -I${GTKHTML_DATA}/gtkhtml ${GTKHTML_DATA}/Editor.idl' % (editor_dir, src_dir), env)
        print cmd
        # generate
        os.system(cmd)


def build(bld):

    source = 'slib-editor.c link_dialog.c' if bld.env['HAVE_EDITOR_IDL'] else \
        'bonobo-editor.c Editor-common.c Editor-skels.c Editor-stubs.c'

    bld.new_task_gen(
        features='cc cxx', # compile C with gcc, C++ with g++
        includes='. ../../ ../../src ../../src/editor %s' %
            bld.env['GECKO_INCLUDE'], # ../../ for config.h
        source=source,
        target='editor',
        #uselib='GLIB GNOMEUI SWORD GTKMOZEMBED GTKMOZEMBED_UNSTABLE GTKHTML GTKHTML_EDITOR'
        uselib= bld.env['ALL_LIBS'],
    )

