#!/usr/bin/env python
# encoding: utf8


if bld.env['ENABLE_WEBKIT_EDITOR']:
    source = 'link_dialog.c editor.c webkit_editor.c'
else:
    source = 'slib-editor.c link_dialog.c'

bld.new_task_gen(
    features='cc cxx', # compile C with gcc, C++ with g++
    includes='. ../../ ../../src ../../src/editor %s' %
    bld.env['GECKO_INCLUDE'], # ../../ for config.h
    source=source,
    target='editor',
    #uselib='GLIB GNOMEUI SWORD GTKMOZEMBED GTKMOZEMBED_UNSTABLE GTKHTML GTKHTML_EDITOR'
    uselib= bld.env['ALL_LIBS'],
)

