#!/usr/bin/env python
# encoding: utf8

import os, os.path


def configure(conf):

    import Utils
    env = conf.env
    sub = Utils.subst_vars
        
    if not env['HAVE_GTKHTML3_23']:
        # generade src files from IDL - must be run before compilation
        src_dir =os.getcwd()
        editor_dir = os.path.join(src_dir, 'src', 'editor')
            
        cmd = sub('${ORBIT_IDL} --output-dir=%s -I%s ${BONOBO_IDL_INCLUDES} -I${GTKHTML_DATA}/gtkhtml ${GTKHTML_DATA}/Editor.idl' % (editor_dir, src_dir), env)
        # generate
        os.system(cmd)

def build(bld):

    lib = bld.new_task_gen(
        features='cc cxx', # use C compiler - less restrictive than C++
        includes='. ../../ ../../src ../../src/editor %s' % bld.env['GECKO_INCLUDE'], # ../../ for config.h
        target='editor',
        uselib='GTK GLIB GNOMEUI SWORD GTKMOZEMBED GTKMOZEMBED_UNSTABLE GTKHTML GTKHTML_EDITOR',
        before='%s/src/editor/Editor.h' % os.getcwd(), # let first generate C sources for Editor
    )

    lib.find_sources_in_dirs('.')

