.TH XIPHOS "1" "Sep 2017" "xiphos 4.0.7" "User Commands"
.SH NAME
xiphos \- A Bible research tool
.SH SYNOPSIS
.B xiphos [OPTION...]

.SH DESCRIPTION
.B Xiphos
is a Bible study application for GTK+ environments, a widget set which
is available for several Unix and Linux flavors. It is based on Sword by the
CrossWire Bible Society, a framework providing the possibility to study the
Bible and additional information like commentaries, dictionaries and other
texts using your computer. Display multiple translations in the interlinear
window. Search for passages in any translation by word, phrase, or regular
expression.
.PP
The program can be started from the command line as
.B xiphos
or from one of the menus provided by the underlying platform.
.P
When started on the command line,
.B xiphos
may be followed by the options listed below.
.SH "OPTIONS"
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-\-display\fR=\fI\,DISPLAY\/\fR
X display to use
.SH "SEE ALSO"
The full documentation for
.B xiphos
can be found online at http://xiphos.org/manual/ or on your system through the
help menu in
.SH "BUGS"
Please report bugs online at: https://github.com/crosswire/xiphos/issues
.SH "AUTHOR"
.B xiphos
was written by the Xiphos Developer Team. <xiphos-devel@crosswire.org>
.PP
