/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "Spell.h"

void
_ORBIT_skel_small_GNOME_Spell_Dictionary_getLanguages
   (POA_GNOME_Spell_Dictionary * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    GNOME_Spell_LanguageSeq *
    (*_impl_getLanguages) (PortableServer_Servant _servant,
			   CORBA_Environment * ev))
{
   *(GNOME_Spell_LanguageSeq * *)_o_retval =
      _impl_getLanguages(_o_servant, _o_ev);
}

void
_ORBIT_skel_small_GNOME_Spell_Dictionary_setLanguage
   (POA_GNOME_Spell_Dictionary * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    void (*_impl_setLanguage) (PortableServer_Servant _servant,
			       const CORBA_char * language,
			       CORBA_Environment * ev))
{
   _impl_setLanguage(_o_servant, *(const CORBA_char * *) _o_args[0], _o_ev);
}

void
_ORBIT_skel_small_GNOME_Spell_Dictionary_checkWord(POA_GNOME_Spell_Dictionary
						   * _o_servant,
						   gpointer _o_retval,
						   gpointer * _o_args,
						   CORBA_Context _o_ctx,
						   CORBA_Environment * _o_ev,
						   CORBA_boolean
						   (*_impl_checkWord)
						   (PortableServer_Servant
						    _servant,
						    const CORBA_char * word,
						    CORBA_Environment * ev))
{
   *(CORBA_boolean *) _o_retval =
      _impl_checkWord(_o_servant, *(const CORBA_char * *) _o_args[0], _o_ev);
}

void
_ORBIT_skel_small_GNOME_Spell_Dictionary_getSuggestions
   (POA_GNOME_Spell_Dictionary * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    GNOME_Spell_StringSeq *
    (*_impl_getSuggestions) (PortableServer_Servant _servant,
			     const CORBA_char * word, CORBA_Environment * ev))
{
   *(GNOME_Spell_StringSeq * *)_o_retval =
      _impl_getSuggestions(_o_servant, *(const CORBA_char * *) _o_args[0],
			   _o_ev);
}

void
_ORBIT_skel_small_GNOME_Spell_Dictionary_addWordToSession
   (POA_GNOME_Spell_Dictionary * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    void (*_impl_addWordToSession) (PortableServer_Servant _servant,
				    const CORBA_char * word,
				    CORBA_Environment * ev))
{
   _impl_addWordToSession(_o_servant, *(const CORBA_char * *) _o_args[0],
			  _o_ev);
}

void
_ORBIT_skel_small_GNOME_Spell_Dictionary_addWordToPersonal
   (POA_GNOME_Spell_Dictionary * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    void (*_impl_addWordToPersonal) (PortableServer_Servant _servant,
				     const CORBA_char * word,
				     const CORBA_char * language,
				     CORBA_Environment * ev))
{
   _impl_addWordToPersonal(_o_servant, *(const CORBA_char * *) _o_args[0],
			   *(const CORBA_char * *) _o_args[1], _o_ev);
}

void
_ORBIT_skel_small_GNOME_Spell_Dictionary_setCorrection
   (POA_GNOME_Spell_Dictionary * _o_servant, gpointer _o_retval,
    gpointer * _o_args, CORBA_Context _o_ctx, CORBA_Environment * _o_ev,
    void (*_impl_setCorrection) (PortableServer_Servant _servant,
				 const CORBA_char * word,
				 const CORBA_char * replacement,
				 const CORBA_char * language,
				 CORBA_Environment * ev))
{
   _impl_setCorrection(_o_servant, *(const CORBA_char * *) _o_args[0],
		       *(const CORBA_char * *) _o_args[1],
		       *(const CORBA_char * *) _o_args[2], _o_ev);
}
static ORBitSmallSkeleton
get_skel_small_GNOME_Spell_Dictionary(POA_GNOME_Spell_Dictionary * servant,
				      const char *opname, gpointer * m_data,
				      gpointer * impl)
{
   switch (opname[0]) {
     case 'a':
	switch (opname[1]) {
	  case 'd':
	     switch (opname[2]) {
	       case 'd':
		  switch (opname[3]) {
		    case 'W':
		       switch (opname[4]) {
			 case 'o':
			    switch (opname[5]) {
			      case 'r':
				 switch (opname[6]) {
				   case 'd':
				      switch (opname[7]) {
					case 'T':
					   switch (opname[8]) {
					     case 'o':
						switch (opname[9]) {
						  case 'P':
						     if (strcmp
							 ((opname + 10),
							  "ersonal"))
							break;
						     *impl =
							(gpointer) servant->
							vepv->
							GNOME_Spell_Dictionary_epv->
							addWordToPersonal;
						     *m_data =
							(gpointer) &
							GNOME_Spell_Dictionary__iinterface.
							methods._buffer[5];
						     return
							(ORBitSmallSkeleton)
							_ORBIT_skel_small_GNOME_Spell_Dictionary_addWordToPersonal;
						     break;
						  case 'S':
						     if (strcmp
							 ((opname + 10),
							  "ession"))
							break;
						     *impl =
							(gpointer) servant->
							vepv->
							GNOME_Spell_Dictionary_epv->
							addWordToSession;
						     *m_data =
							(gpointer) &
							GNOME_Spell_Dictionary__iinterface.
							methods._buffer[4];
						     return
							(ORBitSmallSkeleton)
							_ORBIT_skel_small_GNOME_Spell_Dictionary_addWordToSession;
						     break;
						  default:
						     break;
						}
						break;
					     default:
						break;
					   }
					   break;
					default:
					   break;
				      }
				      break;
				   default:
				      break;
				 }
				 break;
			      default:
				 break;
			    }
			    break;
			 default:
			    break;
		       }
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'c':
	if (strcmp((opname + 1), "heckWord"))
	   break;
	*impl =
	   (gpointer) servant->vepv->GNOME_Spell_Dictionary_epv->checkWord;
	*m_data =
	   (gpointer) & GNOME_Spell_Dictionary__iinterface.methods._buffer[2];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_GNOME_Spell_Dictionary_checkWord;
	break;
     case 'g':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case 'L':
		       if (strcmp((opname + 4), "anguages"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  GNOME_Spell_Dictionary_epv->getLanguages;
		       *m_data =
			  (gpointer) & GNOME_Spell_Dictionary__iinterface.
			  methods._buffer[0];
		       return (ORBitSmallSkeleton)
			  _ORBIT_skel_small_GNOME_Spell_Dictionary_getLanguages;
		       break;
		    case 'S':
		       if (strcmp((opname + 4), "uggestions"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  GNOME_Spell_Dictionary_epv->getSuggestions;
		       *m_data =
			  (gpointer) & GNOME_Spell_Dictionary__iinterface.
			  methods._buffer[3];
		       return (ORBitSmallSkeleton)
			  _ORBIT_skel_small_GNOME_Spell_Dictionary_getSuggestions;
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'q':
	if (strcmp((opname + 1), "ueryInterface"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->queryInterface;
	*m_data = (gpointer) & Bonobo_Unknown__iinterface.methods._buffer[2];
	return (ORBitSmallSkeleton)
	   _ORBIT_skel_small_Bonobo_Unknown_queryInterface;
	break;
     case 'r':
	if (strcmp((opname + 1), "ef"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->ref;
	*m_data = (gpointer) & Bonobo_Unknown__iinterface.methods._buffer[0];
	return (ORBitSmallSkeleton) _ORBIT_skel_small_Bonobo_Unknown_ref;
	break;
     case 's':
	switch (opname[1]) {
	  case 'e':
	     switch (opname[2]) {
	       case 't':
		  switch (opname[3]) {
		    case 'C':
		       if (strcmp((opname + 4), "orrection"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  GNOME_Spell_Dictionary_epv->setCorrection;
		       *m_data =
			  (gpointer) & GNOME_Spell_Dictionary__iinterface.
			  methods._buffer[6];
		       return (ORBitSmallSkeleton)
			  _ORBIT_skel_small_GNOME_Spell_Dictionary_setCorrection;
		       break;
		    case 'L':
		       if (strcmp((opname + 4), "anguage"))
			  break;
		       *impl =
			  (gpointer) servant->vepv->
			  GNOME_Spell_Dictionary_epv->setLanguage;
		       *m_data =
			  (gpointer) & GNOME_Spell_Dictionary__iinterface.
			  methods._buffer[1];
		       return (ORBitSmallSkeleton)
			  _ORBIT_skel_small_GNOME_Spell_Dictionary_setLanguage;
		       break;
		    default:
		       break;
		  }
		  break;
	       default:
		  break;
	     }
	     break;
	  default:
	     break;
	}
	break;
     case 'u':
	if (strcmp((opname + 1), "nref"))
	   break;
	*impl = (gpointer) servant->vepv->Bonobo_Unknown_epv->unref;
	*m_data = (gpointer) & Bonobo_Unknown__iinterface.methods._buffer[1];
	return (ORBitSmallSkeleton) _ORBIT_skel_small_Bonobo_Unknown_unref;
	break;
     default:
	break;
   }
   return NULL;
}

void
POA_GNOME_Spell_Dictionary__init(PortableServer_Servant servant,
				 CORBA_Environment * env)
{
   static PortableServer_ClassInfo class_info =
      { NULL,
(ORBit_small_impl_finder) & get_skel_small_GNOME_Spell_Dictionary, "IDL:GNOME/Spell/Dictionary:1.0",
&GNOME_Spell_Dictionary__classid, NULL, &GNOME_Spell_Dictionary__iinterface };
   POA_GNOME_Spell_Dictionary__vepv *fakevepv = NULL;

   if (((PortableServer_ServantBase *) servant)->vepv[0]->finalize == 0) {
      ((PortableServer_ServantBase *) servant)->vepv[0]->finalize =
	 POA_GNOME_Spell_Dictionary__fini;
   }
   PortableServer_ServantBase__init(((PortableServer_ServantBase *) servant),
				    env);
   POA_Bonobo_Unknown__init(servant, env);
   ORBit_classinfo_register(&class_info);
   ORBIT_SERVANT_SET_CLASSINFO(servant, &class_info);

   if (!class_info.vepvmap) {
      class_info.vepvmap =
	 g_new0(ORBit_VepvIdx, GNOME_Spell_Dictionary__classid + 1);
      class_info.vepvmap[Bonobo_Unknown__classid] =
	 (((char *) &(fakevepv->Bonobo_Unknown_epv)) -
	  ((char *) (fakevepv))) / sizeof(GFunc);
      class_info.vepvmap[GNOME_Spell_Dictionary__classid] =
	 (((char *) &(fakevepv->GNOME_Spell_Dictionary_epv)) -
	  ((char *) (fakevepv))) / sizeof(GFunc);
   }
}

void
POA_GNOME_Spell_Dictionary__fini(PortableServer_Servant servant,
				 CORBA_Environment * env)
{
   POA_Bonobo_Unknown__fini(servant, env);
   PortableServer_ServantBase__fini(servant, env);
}
