#! /usr/bin/env python
# encoding: utf-8

DOC_LINGUAS = '''
    fr
    fa
'''
DOC_INCLUDES = '''
    introduction.xml
    interface.xml
    start.xml
    preferences.xml
    modules.xml
    search.xml
    studypad.xml
    personal.xml
    journals.xml
    onlinehelp.xml
    originallanguage.xml
'''
DOC_FIGURES = '''
    figures/first_start.png
    figures/gtkhtml3-vs-mozembed.png
    figures/interface_biblepane-options.png
    figures/interface_biblepane.png
    figures/interface_commentarypane.png
    figures/interface_dictionary.png
    figures/interface_menubar.png
    figures/interface_menubar-view.png
    figures/interface_parallel.png
    figures/interface_parallel-separate.png
    figures/interface.png
    figures/interface_searchpane.png
    figures/interface_shortcut.png
    figures/interface_sidepane.png
    figures/interface_toolbar.png
    figures/interface_viewer.png
    figures/journal.png
    figures/module.png
    figures/personal.png
    figures/preferences_fonts-color.png
    figures/preferences_fonts-misc.png
    figures/preferences_general-misc.png
    figures/preferences_general-biblesync.png
    figures/preferences_modules-misc.png
    figures/preferences_modules-parallel.png
    figures/preferences.png
    figures/search_search.png
    figures/studypad.png
    figures/sword3.png
    figures/sword_config.png
    figures/sword_install.png
    figures/sword_remove.png
    figures/sword_sources.png
'''

if not bld.env['DISABLE_HELP']:
    if bld.env['IS_LINUX']:
        obj = bld.new_task_gen('gnome_doc')
    else:
        obj = bld.new_task_gen('xml_doc')
    obj.doc_module = 'xiphos'
    obj.doc_entities = 'legal.xml'
    obj.doc_includes = DOC_INCLUDES
    obj.doc_figures = DOC_FIGURES
    obj.doc_linguas = DOC_LINGUAS

