#!/usr/bin/env python
# encoding: utf8

lib = bld.new_task_gen(
    features='cxx cc',
    includes = '. ../.. ../../src',
    target='backend',
    #uselib='GLIB GNOMEUI SWORD',
    uselib= bld.env['ALL_LIBS'],
)

lib.find_sources_in_dirs('.')
