#!/usr/bin/env python
# encoding: utf8

lib = bld.new_task_gen(
    features='cxx cc',
    includes='. ../.. ../../src %s' % bld.env['GNOME_INCLUDE'],
    target='xiphos_html',
    uselib= bld.env['ALL_LIBS'],
)

if not bld.env['WITHOUT_DBUS']:
    lib.add_marshal_file('marshal.list', 'xihtml_marshal')
lib.find_sources_in_dirs('.')

	
