/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "callback.h"
#include "interface.h"
#include "support.h"

static GnomeUIInfo menu1_uiinfo[] =
{
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy3_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

GtkWidget*
create_menu1 (void)
{
  GtkWidget *menu1;

  menu1 = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (menu1), "menu1", menu1);
  gnome_app_fill_menu (GTK_MENU_SHELL (menu1), menu1_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_ref (menu1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (menu1), "copy1",
                            menu1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menu1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (menu1), "separator2",
                            menu1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  return menu1;
}

static GnomeUIInfo file1_menu_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_exit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo edit1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, "Copy",
    "Copy high lighted text form main window",
    on_copy1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, "Search",
    "Open search dialog",
    on_search1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, "Verse List",
    "Open Verse List ",
    on_verse_list1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_INDEX,
    0, 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo bookmarks1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, "Add Bookmark",
    "Add current verse to bookmarks menu",
    on_add_bookmark1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_BOOK_RED,
    0, 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, "Edit Bookmarks",
    "Edit bookmarks list",
    on_edit_bookmarks1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_BOOK_GREEN,
    0, 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo history1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, "C_lear",
    "Clear history list",
    on_clear1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo main_window1_menu_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo interlinear1_window1_menu_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo interlinear2_window1_menu_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo interlinear3_window1_menu_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo view1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, "Main Window",
    "Select text module for main window",
    main_window1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "Main Window",
    0, 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, "Interlinear1 Window",
    "Select text module for 1st Interlinear window",
    interlinear1_window1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "Interlinear1 Window",
    0, 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, "Interlinear2 Window",
    "Select text module for 2nd Interlinear window",
    interlinear2_window1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "Interlinear2 Window",
    0, 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, "Interlinear3 Window",
    "Select text module for 3rd Interlinear window",
    interlinear3_window1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "Interlinear3 Window",
    0, 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo settings1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_PREFERENCES_ITEM (on_preferences1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo bible_texts1_menu_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo commentaries1_menu_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo dictionaries_lexicons1_menu_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

static GnomeUIInfo about_sword_modules1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, "Bible Texts",
    "Information about Bible texts",
    bible_texts1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "Bible Texts",
    0, 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, "Commentaries",
    NULL,
    commentaries1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "Commentaries",
    0, 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, "Dictionaries-Lexicons",
    NULL,
    dictionaries_lexicons1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "Dictionaries-Lexicons",
    0, 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, "About the Sword Project...",
    "About The Sword Project",
    on_about_the_sword_project1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_ABOUT,
    0, 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, "About GnomeSword...",
    "About GnomeSword",
    on_about_gnomesword1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, GNOME_STOCK_MENU_ABOUT,
    0, 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, "About Sword Modules",
    "Information about the installed modules",
    about_sword_modules1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "About Sword Modules",
    0, 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  GNOMEUIINFO_MENU_FILE_TREE (file1_menu_uiinfo),
  GNOMEUIINFO_MENU_EDIT_TREE (edit1_menu_uiinfo),
  {
    GNOME_APP_UI_SUBTREE, "_Bookmarks",
    NULL,
    bookmarks1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "_Bookmarks",
    0, 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, "_History",
    NULL,
    history1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, "_History",
    0, 0, NULL
  },
  GNOMEUIINFO_MENU_VIEW_TREE (view1_menu_uiinfo),
  GNOMEUIINFO_MENU_SETTINGS_TREE (settings1_menu_uiinfo),
  GNOMEUIINFO_MENU_HELP_TREE (help1_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *dock1;
  GtkWidget *toolbar20;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *btnSearch;
  GtkWidget *btnStrongs;
  GtkWidget *cbBook;
  GList *cbBook_items = NULL;
  GtkWidget *cbeBook;
  GtkObject *spbChapter_adj;
  GtkWidget *spbChapter;
  GtkObject *spbVerse_adj;
  GtkWidget *spbVerse;
  GtkWidget *cbeFreeformLookup;
  GtkWidget *btnLookup;
  GtkWidget *vseparator13;
  GtkWidget *btnExit;
  GtkWidget *mainPanel;
  GtkWidget *vpaned1;
  GtkWidget *hbox2;
  GtkWidget *hpaned1;
  GtkWidget *frame9;
  GtkWidget *vbox19;
  GtkWidget *scrolledwindow18;
  GtkWidget *moduleText;
  GtkWidget *frame19;
  GtkWidget *lbText;
  GtkWidget *notebook3;
  GtkWidget *vbox22;
  GtkWidget *notebook1;
  GtkWidget *hbox18;
  GtkWidget *vbox23;
  GtkWidget *scrolledwindow28;
  GtkWidget *textCommentaries;
  GtkWidget *label64;
  GtkWidget *vbox2;
  GtkWidget *hbox11;
  GtkWidget *vbox8;
  GtkWidget *scrolledwindow11;
  GtkWidget *textComments;
  GtkWidget *sbNotes;
  GtkWidget *handlebox16;
  GtkWidget *tbNotes;
  GtkWidget *btnEditNote;
  GtkWidget *btnSaveNote;
  GtkWidget *btnDeleteNote;
  GtkWidget *btnSpellNotes;
  GtkWidget *label85;
  GtkWidget *vbox3;
  GtkWidget *frame2;
  GtkWidget *vbox4;
  GtkWidget *scrolledwindow15;
  GtkWidget *textComp1;
  GtkWidget *frame17;
  GtkWidget *scrolledwindow16;
  GtkWidget *textComp2;
  GtkWidget *frame18;
  GtkWidget *scrolledwindow21;
  GtkWidget *textComp3;
  GtkWidget *label12;
  GtkWidget *frame12;
  GtkWidget *vbox6;
  GtkWidget *handlebox10;
  GtkWidget *toolbar5;
  GtkWidget *btnOpenFile;
  GtkWidget *btnSaveFile;
  GtkWidget *btnSaveFileAs;
  GtkWidget *vseparator9;
  GtkWidget *btnPrint;
  GtkWidget *vseparator10;
  GtkWidget *btnCut;
  GtkWidget *btnCopy;
  GtkWidget *btnPaste;
  GtkWidget *vseparator11;
  GtkWidget *btnSpell;
  GtkWidget *scrolledwindow17;
  GtkWidget *text3;
  GtkWidget *statusbar2;
  GtkWidget *label41;
  GtkWidget *hbox8;
  GtkWidget *frame10;
  GtkWidget *hbox13;
  GtkWidget *vbox1;
  GtkWidget *notebook4;
  GtkWidget *scrolledwindow8;
  GtkWidget *textDict;
  GtkWidget *vbox14;
  GtkWidget *hbox19;
  GtkWidget *toolbar25;
  GtkWidget *btnKeyPrev;
  GtkWidget *dictionarySearchText;
  GtkWidget *btnKeyNext;
  GtkWidget *list1;
  GtkWidget *label58;
  GtkWidget *appbar1;

  mainwindow = gnome_app_new ("gnomesword", "GnomeSword - Bible Study Software");
  gtk_object_set_data (GTK_OBJECT (mainwindow), "mainwindow", mainwindow);
  gtk_widget_set_usize (mainwindow, 640, 480);
  GTK_WIDGET_SET_FLAGS (mainwindow, GTK_CAN_FOCUS);
  gtk_window_set_default_size (GTK_WINDOW (mainwindow), 640, 480);

  dock1 = GNOME_APP (mainwindow)->dock;
  gtk_widget_ref (dock1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "dock1", dock1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dock1);

  gnome_app_create_menus (GNOME_APP (mainwindow), menubar1_uiinfo);

  gtk_widget_ref (menubar1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "file1",
                            menubar1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator4",
                            file1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (file1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "exit1",
                            file1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "edit1",
                            menubar1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "copy1",
                            edit1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator3",
                            edit1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "search1",
                            edit1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator14",
                            edit1_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit1_menu_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "verse_list1",
                            edit1_menu_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "bookmarks1",
                            menubar1_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (bookmarks1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "add_bookmark1",
                            bookmarks1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (bookmarks1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "edit_bookmarks1",
                            bookmarks1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (bookmarks1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator4",
                            bookmarks1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "history1",
                            menubar1_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (history1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "clear1",
                            history1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (history1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator5",
                            history1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[4].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "view1",
                            menubar1_uiinfo[4].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (view1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "main_window1",
                            view1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (main_window1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator8",
                            main_window1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (view1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "interlinear1_window1",
                            view1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (interlinear1_window1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator10",
                            interlinear1_window1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (view1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "interlinear2_window1",
                            view1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (interlinear2_window1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator9",
                            interlinear2_window1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (view1_menu_uiinfo[3].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "interlinear3_window1",
                            view1_menu_uiinfo[3].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (interlinear3_window1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator11",
                            interlinear3_window1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[5].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "settings1",
                            menubar1_uiinfo[5].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (settings1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "preferences1",
                            settings1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menubar1_uiinfo[6].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "help1",
                            menubar1_uiinfo[6].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "about_the_sword_project1",
                            help1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "about_gnomesword1",
                            help1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (help1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "about_sword_modules1",
                            help1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (about_sword_modules1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "bible_texts1",
                            about_sword_modules1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (bible_texts1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator15",
                            bible_texts1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (about_sword_modules1_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "commentaries1",
                            about_sword_modules1_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (commentaries1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator16",
                            commentaries1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (about_sword_modules1_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "dictionaries_lexicons1",
                            about_sword_modules1_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (dictionaries_lexicons1_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "separator17",
                            dictionaries_lexicons1_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  toolbar20 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_ref (toolbar20);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "toolbar20", toolbar20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar20);
  gnome_app_add_toolbar (GNOME_APP (mainwindow), GTK_TOOLBAR (toolbar20), "toolbar20",
                                GNOME_DOCK_ITEM_BEH_NEVER_VERTICAL,
                                GNOME_DOCK_TOP, 1, 0, 0);
  gtk_widget_set_usize (toolbar20, -2, 34);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar20), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_SEARCH);
  btnSearch = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar20),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Search",
                                "Search current text or commentary module", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnSearch);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnSearch", btnSearch,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnSearch);

  tmp_toolbar_icon = create_pixmap (mainwindow, "gnomesword/strongs2.xpm", TRUE);
  btnStrongs = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar20),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                "Strongs",
                                "Toogle Strongs Numbers", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnStrongs);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnStrongs", btnStrongs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnStrongs);

  cbBook = gtk_combo_new ();
  gtk_widget_ref (cbBook);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "cbBook", cbBook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cbBook);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar20), cbBook, NULL, NULL);
  gtk_widget_set_usize (cbBook, 154, -2);
  cbBook_items = g_list_append (cbBook_items, "Genesis");
  cbBook_items = g_list_append (cbBook_items, "Exodus");
  cbBook_items = g_list_append (cbBook_items, "Leviticus");
  cbBook_items = g_list_append (cbBook_items, "Numbers");
  cbBook_items = g_list_append (cbBook_items, "Deuteronomy");
  cbBook_items = g_list_append (cbBook_items, "Joshua");
  cbBook_items = g_list_append (cbBook_items, "Judges");
  cbBook_items = g_list_append (cbBook_items, "Ruth");
  cbBook_items = g_list_append (cbBook_items, "I Samuel");
  cbBook_items = g_list_append (cbBook_items, "II Samuel");
  cbBook_items = g_list_append (cbBook_items, "I Kings");
  cbBook_items = g_list_append (cbBook_items, "II Kings");
  cbBook_items = g_list_append (cbBook_items, "I Chronicles");
  cbBook_items = g_list_append (cbBook_items, "II Chronicles");
  cbBook_items = g_list_append (cbBook_items, "Ezra");
  cbBook_items = g_list_append (cbBook_items, "Nehemiah");
  cbBook_items = g_list_append (cbBook_items, "Esther");
  cbBook_items = g_list_append (cbBook_items, "Job");
  cbBook_items = g_list_append (cbBook_items, "Psalms");
  cbBook_items = g_list_append (cbBook_items, "Proverbs");
  cbBook_items = g_list_append (cbBook_items, "Ecclesiastes");
  cbBook_items = g_list_append (cbBook_items, "Song of Solomon");
  cbBook_items = g_list_append (cbBook_items, "Isaiah");
  cbBook_items = g_list_append (cbBook_items, "Jeremiah");
  cbBook_items = g_list_append (cbBook_items, "Lamentations");
  cbBook_items = g_list_append (cbBook_items, "Ezekiel");
  cbBook_items = g_list_append (cbBook_items, "Daniel");
  cbBook_items = g_list_append (cbBook_items, "Hosea");
  cbBook_items = g_list_append (cbBook_items, "Joel");
  cbBook_items = g_list_append (cbBook_items, "Amos");
  cbBook_items = g_list_append (cbBook_items, "Obadiah");
  cbBook_items = g_list_append (cbBook_items, "Jonah");
  cbBook_items = g_list_append (cbBook_items, "Micah");
  cbBook_items = g_list_append (cbBook_items, "Nahum");
  cbBook_items = g_list_append (cbBook_items, "Habakkuk");
  cbBook_items = g_list_append (cbBook_items, "Zephaniah");
  cbBook_items = g_list_append (cbBook_items, "Haggai");
  cbBook_items = g_list_append (cbBook_items, "Zechariah");
  cbBook_items = g_list_append (cbBook_items, "Malachi");
  cbBook_items = g_list_append (cbBook_items, "Matthew");
  cbBook_items = g_list_append (cbBook_items, "Mark");
  cbBook_items = g_list_append (cbBook_items, "Luke");
  cbBook_items = g_list_append (cbBook_items, "John");
  cbBook_items = g_list_append (cbBook_items, "Acts");
  cbBook_items = g_list_append (cbBook_items, "Romans");
  cbBook_items = g_list_append (cbBook_items, "I Corinthians");
  cbBook_items = g_list_append (cbBook_items, "II Corinthians");
  cbBook_items = g_list_append (cbBook_items, "Galatians");
  cbBook_items = g_list_append (cbBook_items, "Ephesians");
  cbBook_items = g_list_append (cbBook_items, "Philippians");
  cbBook_items = g_list_append (cbBook_items, "Colossians");
  cbBook_items = g_list_append (cbBook_items, "I Thessalonians");
  cbBook_items = g_list_append (cbBook_items, "II Thessalonians");
  cbBook_items = g_list_append (cbBook_items, "I Timothy");
  cbBook_items = g_list_append (cbBook_items, "II Timothy");
  cbBook_items = g_list_append (cbBook_items, "Titus");
  cbBook_items = g_list_append (cbBook_items, "Philemon");
  cbBook_items = g_list_append (cbBook_items, "Hebrews");
  cbBook_items = g_list_append (cbBook_items, "James");
  cbBook_items = g_list_append (cbBook_items, "I Peter");
  cbBook_items = g_list_append (cbBook_items, "II Peter");
  cbBook_items = g_list_append (cbBook_items, "I John");
  cbBook_items = g_list_append (cbBook_items, "II John");
  cbBook_items = g_list_append (cbBook_items, "III John");
  cbBook_items = g_list_append (cbBook_items, "Jude");
  cbBook_items = g_list_append (cbBook_items, "Revelation");
  gtk_combo_set_popdown_strings (GTK_COMBO (cbBook), cbBook_items);
  g_list_free (cbBook_items);

  cbeBook = GTK_COMBO (cbBook)->entry;
  gtk_widget_ref (cbeBook);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "cbeBook", cbeBook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cbeBook);
  gtk_entry_set_text (GTK_ENTRY (cbeBook), "Romans");

  spbChapter_adj = gtk_adjustment_new (8, 0, 150, 1, 10, 10);
  spbChapter = gtk_spin_button_new (GTK_ADJUSTMENT (spbChapter_adj), 1, 0);
  gtk_widget_ref (spbChapter);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "spbChapter", spbChapter,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spbChapter);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar20), spbChapter, NULL, NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spbChapter), TRUE);

  spbVerse_adj = gtk_adjustment_new (28, 0, 100, 1, 10, 10);
  spbVerse = gtk_spin_button_new (GTK_ADJUSTMENT (spbVerse_adj), 1, 0);
  gtk_widget_ref (spbVerse);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "spbVerse", spbVerse,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (spbVerse);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar20), spbVerse, NULL, NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spbVerse), TRUE);

  cbeFreeformLookup = gtk_entry_new ();
  gtk_widget_ref (cbeFreeformLookup);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "cbeFreeformLookup", cbeFreeformLookup,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cbeFreeformLookup);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar20), cbeFreeformLookup, NULL, NULL);
  gtk_widget_set_usize (cbeFreeformLookup, 190, -2);
  gtk_entry_set_text (GTK_ENTRY (cbeFreeformLookup), "Romans 8:28");

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_JUMP_TO);
  btnLookup = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar20),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "button1",
                                "Go to verse in free form lookup and add verse to history", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnLookup);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnLookup", btnLookup,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnLookup);

  vseparator13 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator13);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vseparator13", vseparator13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator13);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar20), vseparator13, NULL, NULL);
  gtk_widget_set_usize (vseparator13, 7, 7);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_EXIT);
  btnExit = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar20),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Exit",
                                "Exit GnomeSword", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnExit);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnExit", btnExit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnExit);

  mainPanel = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (mainPanel);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "mainPanel", mainPanel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mainPanel);
  gnome_app_set_contents (GNOME_APP (mainwindow), mainPanel);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_ref (vpaned1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vpaned1", vpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vpaned1);
  gtk_box_pack_start (GTK_BOX (mainPanel), vpaned1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vpaned1), 1);
  gtk_paned_set_gutter_size (GTK_PANED (vpaned1), 10);
  gtk_paned_set_position (GTK_PANED (vpaned1), 236);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (vpaned1), hbox2);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hpaned1", hpaned1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_end (GTK_BOX (hbox2), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_gutter_size (GTK_PANED (hpaned1), 10);

  frame9 = gtk_frame_new ("KJV");
  gtk_widget_ref (frame9);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "frame9", frame9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame9);
  gtk_container_add (GTK_CONTAINER (hpaned1), frame9);
  gtk_widget_set_usize (frame9, 325, -2);
  gtk_container_set_border_width (GTK_CONTAINER (frame9), 2);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox19);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox19", vbox19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox19);
  gtk_container_add (GTK_CONTAINER (frame9), vbox19);

  scrolledwindow18 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow18);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "scrolledwindow18", scrolledwindow18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow18);
  gtk_box_pack_start (GTK_BOX (vbox19), scrolledwindow18, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow18), 2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow18), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  moduleText = gtk_text_new (NULL, NULL);
  gtk_widget_ref (moduleText);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "moduleText", moduleText,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (moduleText);
  gtk_container_add (GTK_CONTAINER (scrolledwindow18), moduleText);

  frame19 = gtk_frame_new (NULL);
  gtk_widget_ref (frame19);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "frame19", frame19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame19);
  gtk_box_pack_start (GTK_BOX (vbox19), frame19, FALSE, FALSE, 0);

  lbText = gtk_label_new ("[KJV]");
  gtk_widget_ref (lbText);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "lbText", lbText,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lbText);
  gtk_container_add (GTK_CONTAINER (frame19), lbText);
  gtk_misc_set_padding (GTK_MISC (lbText), 1, 1);

  notebook3 = gtk_notebook_new ();
  gtk_widget_ref (notebook3);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "notebook3", notebook3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook3);
  gtk_container_add (GTK_CONTAINER (hpaned1), notebook3);
  gtk_container_set_border_width (GTK_CONTAINER (notebook3), 2);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook3), TRUE);

  vbox22 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox22);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox22", vbox22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox22);
  gtk_container_add (GTK_CONTAINER (notebook3), vbox22);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox22), notebook1, FALSE, TRUE, 0);
  gtk_widget_set_usize (notebook1, -2, 31);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook1), TRUE);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox18);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hbox18", hbox18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox22), hbox18, TRUE, TRUE, 0);

  vbox23 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox23);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox23", vbox23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox23);
  gtk_box_pack_start (GTK_BOX (hbox18), vbox23, TRUE, TRUE, 0);

  scrolledwindow28 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow28);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "scrolledwindow28", scrolledwindow28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow28);
  gtk_box_pack_start (GTK_BOX (vbox23), scrolledwindow28, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow28), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textCommentaries = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textCommentaries);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "textCommentaries", textCommentaries,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textCommentaries);
  gtk_container_add (GTK_CONTAINER (scrolledwindow28), textCommentaries);

  label64 = gtk_label_new ("Commentaries");
  gtk_widget_ref (label64);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "label64", label64,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label64);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label64);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_container_add (GTK_CONTAINER (notebook3), vbox2);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox11);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hbox11", hbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox11, TRUE, TRUE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox11), vbox8, TRUE, TRUE, 0);

  scrolledwindow11 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow11);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "scrolledwindow11", scrolledwindow11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow11);
  gtk_box_pack_start (GTK_BOX (vbox8), scrolledwindow11, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow11), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textComments = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textComments);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "textComments", textComments,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textComments);
  gtk_container_add (GTK_CONTAINER (scrolledwindow11), textComments);

  sbNotes = gtk_statusbar_new ();
  gtk_widget_ref (sbNotes);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "sbNotes", sbNotes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (vbox8), sbNotes, FALSE, FALSE, 0);

  handlebox16 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox16);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "handlebox16", handlebox16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox16);
  gtk_box_pack_start (GTK_BOX (hbox11), handlebox16, FALSE, FALSE, 0);
  gtk_handle_box_set_shadow_type (GTK_HANDLE_BOX (handlebox16), GTK_SHADOW_NONE);
  gtk_handle_box_set_handle_position (GTK_HANDLE_BOX (handlebox16), GTK_POS_TOP);

  tbNotes = gtk_toolbar_new (GTK_ORIENTATION_VERTICAL, GTK_TOOLBAR_ICONS);
  gtk_widget_ref (tbNotes);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "tbNotes", tbNotes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tbNotes);
  gtk_container_add (GTK_CONTAINER (handlebox16), tbNotes);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (tbNotes), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_PROPERTIES);
  btnEditNote = gtk_toolbar_append_element (GTK_TOOLBAR (tbNotes),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                "Edit",
                                "Edit note", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnEditNote);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnEditNote", btnEditNote,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnEditNote);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_ADD);
  btnSaveNote = gtk_toolbar_append_element (GTK_TOOLBAR (tbNotes),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Save",
                                "Save note", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnSaveNote);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnSaveNote", btnSaveNote,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnSaveNote);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_REMOVE);
  btnDeleteNote = gtk_toolbar_append_element (GTK_TOOLBAR (tbNotes),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Delete",
                                "Delete note", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnDeleteNote);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnDeleteNote", btnDeleteNote,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnDeleteNote);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_SPELLCHECK);
  btnSpellNotes = gtk_toolbar_append_element (GTK_TOOLBAR (tbNotes),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "button1",
                                "Start Spell Check", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnSpellNotes);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnSpellNotes", btnSpellNotes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnSpellNotes);

  label85 = gtk_label_new ("Personal Comments");
  gtk_widget_ref (label85);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "label85", label85,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label85);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label85);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook3), vbox3);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox3), frame2, TRUE, TRUE, 0);
  gtk_widget_set_usize (frame2, -2, 67);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (frame2), vbox4);

  scrolledwindow15 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow15);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "scrolledwindow15", scrolledwindow15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow15);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow15, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow15), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textComp1 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textComp1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "textComp1", textComp1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textComp1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow15), textComp1);

  frame17 = gtk_frame_new (NULL);
  gtk_widget_ref (frame17);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "frame17", frame17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame17);
  gtk_box_pack_start (GTK_BOX (vbox3), frame17, TRUE, TRUE, 0);
  gtk_widget_set_usize (frame17, -2, 73);

  scrolledwindow16 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow16);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "scrolledwindow16", scrolledwindow16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow16);
  gtk_container_add (GTK_CONTAINER (frame17), scrolledwindow16);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow16), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textComp2 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textComp2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "textComp2", textComp2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textComp2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow16), textComp2);

  frame18 = gtk_frame_new (NULL);
  gtk_widget_ref (frame18);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "frame18", frame18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame18);
  gtk_box_pack_start (GTK_BOX (vbox3), frame18, TRUE, TRUE, 0);
  gtk_widget_set_usize (frame18, -2, 76);

  scrolledwindow21 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow21);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "scrolledwindow21", scrolledwindow21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow21);
  gtk_container_add (GTK_CONTAINER (frame18), scrolledwindow21);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow21), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textComp3 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textComp3);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "textComp3", textComp3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textComp3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow21), textComp3);

  label12 = gtk_label_new ("Interlinear");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 2), label12);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_ref (frame12);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "frame12", frame12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame12);
  gtk_container_add (GTK_CONTAINER (notebook3), frame12);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (frame12), vbox6);

  handlebox10 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox10);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "handlebox10", handlebox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox10);
  gtk_box_pack_start (GTK_BOX (vbox6), handlebox10, FALSE, TRUE, 0);
  gtk_handle_box_set_shadow_type (GTK_HANDLE_BOX (handlebox10), GTK_SHADOW_NONE);
  gtk_handle_box_set_snap_edge (GTK_HANDLE_BOX (handlebox10), GTK_POS_LEFT);

  toolbar5 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_ref (toolbar5);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "toolbar5", toolbar5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar5);
  gtk_container_add (GTK_CONTAINER (handlebox10), toolbar5);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar5), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_OPEN);
  btnOpenFile = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar5),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Open",
                                "Open File", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnOpenFile);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnOpenFile", btnOpenFile,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnOpenFile);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_SAVE);
  btnSaveFile = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar5),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Save",
                                "Save", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnSaveFile);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnSaveFile", btnSaveFile,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnSaveFile);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_SAVE_AS);
  btnSaveFileAs = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar5),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Save As",
                                "Save as", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnSaveFileAs);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnSaveFileAs", btnSaveFileAs,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnSaveFileAs);

  vseparator9 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator9);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vseparator9", vseparator9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator9);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar5), vseparator9, NULL, NULL);
  gtk_widget_set_usize (vseparator9, 7, 17);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_PRINT);
  btnPrint = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar5),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Print",
                                "Print ", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnPrint);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnPrint", btnPrint,
                            (GtkDestroyNotify) gtk_widget_unref);

  vseparator10 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator10);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vseparator10", vseparator10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator10);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar5), vseparator10, NULL, NULL);
  gtk_widget_set_usize (vseparator10, 7, 17);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_CUT);
  btnCut = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar5),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Cut",
                                "Cut to clipboard", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnCut);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnCut", btnCut,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnCut);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_COPY);
  btnCopy = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar5),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Copy",
                                "Copy to clipboard", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnCopy);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnCopy", btnCopy,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnCopy);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_PASTE);
  btnPaste = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar5),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "Paste",
                                "Paste from clipborad", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnPaste);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnPaste", btnPaste,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnPaste);

  vseparator11 = gtk_vseparator_new ();
  gtk_widget_ref (vseparator11);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vseparator11", vseparator11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vseparator11);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar5), vseparator11, NULL, NULL);
  gtk_widget_set_usize (vseparator11, -2, 17);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_SPELLCHECK);
  btnSpell = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar5),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "button8",
                                "Start Spell Check", NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnSpell);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnSpell", btnSpell,
                            (GtkDestroyNotify) gtk_widget_unref);

  scrolledwindow17 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow17);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "scrolledwindow17", scrolledwindow17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow17);
  gtk_box_pack_start (GTK_BOX (vbox6), scrolledwindow17, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow17), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  text3 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text3);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "text3", text3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow17), text3);
  gtk_text_set_editable (GTK_TEXT (text3), TRUE);

  statusbar2 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "statusbar2", statusbar2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar2);
  gtk_box_pack_start (GTK_BOX (vbox6), statusbar2, FALSE, TRUE, 0);

  label41 = gtk_label_new ("Study Pad");
  gtk_widget_ref (label41);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "label41", label41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label41);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 3), label41);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (vpaned1), hbox8);
  gtk_widget_set_usize (hbox8, -2, 115);

  frame10 = gtk_frame_new ("Dictionaries - Lexicons");
  gtk_widget_ref (frame10);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "frame10", frame10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame10);
  gtk_box_pack_start (GTK_BOX (hbox8), frame10, TRUE, TRUE, 0);
  gtk_widget_set_usize (frame10, -2, 205);
  gtk_container_set_border_width (GTK_CONTAINER (frame10), 2);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox13);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hbox13", hbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (frame10), hbox13);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (hbox13), vbox1, TRUE, TRUE, 0);
  gtk_widget_set_usize (vbox1, 427, -2);

  notebook4 = gtk_notebook_new ();
  gtk_widget_ref (notebook4);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "notebook4", notebook4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook4);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook4, FALSE, TRUE, 0);
  gtk_widget_set_usize (notebook4, -2, 31);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (notebook4), TRUE);

  scrolledwindow8 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow8);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "scrolledwindow8", scrolledwindow8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow8);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow8, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow8), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  textDict = gtk_text_new (NULL, NULL);
  gtk_widget_ref (textDict);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "textDict", textDict,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (textDict);
  gtk_container_add (GTK_CONTAINER (scrolledwindow8), textDict);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox14);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox14", vbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (hbox13), vbox14, FALSE, TRUE, 0);
  gtk_widget_set_usize (vbox14, 208, -2);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox19);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "hbox19", hbox19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox14), hbox19, FALSE, FALSE, 0);

  toolbar25 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_ICONS);
  gtk_widget_ref (toolbar25);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "toolbar25", toolbar25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar25);
  gtk_box_pack_start (GTK_BOX (hbox19), toolbar25, TRUE, TRUE, 0);
  gtk_widget_set_usize (toolbar25, 132, -2);
  gtk_toolbar_set_button_relief (GTK_TOOLBAR (toolbar25), GTK_RELIEF_NONE);

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_BACK);
  btnKeyPrev = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar25),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "button2",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnKeyPrev);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnKeyPrev", btnKeyPrev,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnKeyPrev);

  dictionarySearchText = gtk_entry_new ();
  gtk_widget_ref (dictionarySearchText);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "dictionarySearchText", dictionarySearchText,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (dictionarySearchText);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar25), dictionarySearchText, NULL, NULL);
  gtk_widget_set_usize (dictionarySearchText, 145, -2);
  gtk_entry_set_text (GTK_ENTRY (dictionarySearchText), "GRACE");

  tmp_toolbar_icon = gnome_stock_pixmap_widget (mainwindow, GNOME_STOCK_PIXMAP_FORWARD);
  btnKeyNext = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar25),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                "button3",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_widget_ref (btnKeyNext);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "btnKeyNext", btnKeyNext,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnKeyNext);

  list1 = gtk_clist_new (1);
  gtk_widget_ref (list1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "list1", list1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (list1);
  gtk_box_pack_start (GTK_BOX (vbox14), list1, TRUE, TRUE, 0);
  gtk_widget_set_usize (list1, 126, -2);
  gtk_clist_set_column_width (GTK_CLIST (list1), 0, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (list1));

  label58 = gtk_label_new ("label58");
  gtk_widget_ref (label58);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "label58", label58,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label58);
  gtk_clist_set_column_widget (GTK_CLIST (list1), 0, label58);

  appbar1 = gnome_appbar_new (FALSE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_ref (appbar1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "appbar1", appbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (appbar1);
  gnome_app_set_statusbar (GNOME_APP (mainwindow), appbar1);
  gnome_app_install_menu_hints(GNOME_APP(mainwindow), menubar1_uiinfo);

  gtk_signal_connect (GTK_OBJECT (mainwindow), "destroy",
                      GTK_SIGNAL_FUNC (on_mainwindow_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSearch), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSearch_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnStrongs), "toggled",
                      GTK_SIGNAL_FUNC (on_btnStrongs_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cbBook), "button_release_event",
                      GTK_SIGNAL_FUNC (on_cbBook_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cbBook), "focus",
                      GTK_SIGNAL_FUNC (on_cbBook_focus),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cbeBook), "changed",
                      GTK_SIGNAL_FUNC (on_cbeBook_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (spbChapter), "changed",
                      GTK_SIGNAL_FUNC (on_spbChapter_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (spbChapter), "activate",
                      GTK_SIGNAL_FUNC (on_spbChapter_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (spbChapter), "button_release_event",
                      GTK_SIGNAL_FUNC (on_spbChapter_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (spbVerse), "changed",
                      GTK_SIGNAL_FUNC (on_spbVerse_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (spbVerse), "activate",
                      GTK_SIGNAL_FUNC (on_spbVerse_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (spbVerse), "button_release_event",
                      GTK_SIGNAL_FUNC (on_spbVerse_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cbeFreeformLookup), "key_press_event",
                      GTK_SIGNAL_FUNC (on_cbeFreeformLookup_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnLookup), "clicked",
                      GTK_SIGNAL_FUNC (on_btnLookup_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnExit), "clicked",
                      GTK_SIGNAL_FUNC (on_btnExit_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (moduleText), "button_press_event",
                      GTK_SIGNAL_FUNC (on_moduleText_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (notebook3), "switch_page",
                      GTK_SIGNAL_FUNC (on_notebook3_switch_page),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (notebook1), "switch_page",
                      GTK_SIGNAL_FUNC (on_notebook1_switch_page),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textCommentaries), "changed",
                      GTK_SIGNAL_FUNC (on_textComments_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textCommentaries), "button_release_event",
                      GTK_SIGNAL_FUNC (on_textComments_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textComments), "changed",
                      GTK_SIGNAL_FUNC (on_textComments_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textComments), "button_release_event",
                      GTK_SIGNAL_FUNC (on_textComments_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnEditNote), "toggled",
                      GTK_SIGNAL_FUNC (on_btnEditNote_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSaveNote), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSaveNote_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnDeleteNote), "clicked",
                      GTK_SIGNAL_FUNC (on_btnDeleteNote_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSpellNotes), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSpellNotes_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textComp1), "button_press_event",
                      GTK_SIGNAL_FUNC (on_textComp1_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textComp2), "button_press_event",
                      GTK_SIGNAL_FUNC (on_textComp2_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textComp3), "button_press_event",
                      GTK_SIGNAL_FUNC (on_textComp3_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnOpenFile), "clicked",
                      GTK_SIGNAL_FUNC (on_btnOpenFile_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSaveFile), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSaveFile_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSaveFileAs), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSaveFileAs_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnPrint), "clicked",
                      GTK_SIGNAL_FUNC (on_btnPrint_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnCut), "clicked",
                      GTK_SIGNAL_FUNC (on_btnCut_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnCopy), "clicked",
                      GTK_SIGNAL_FUNC (on_btnCopy_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnPaste), "clicked",
                      GTK_SIGNAL_FUNC (on_btnPaste_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnSpell), "clicked",
                      GTK_SIGNAL_FUNC (on_btnSpell_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (text3), "changed",
                      GTK_SIGNAL_FUNC (on_text3_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (notebook4), "switch_page",
                      GTK_SIGNAL_FUNC (on_notebook4_switch_page),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textDict), "button_press_event",
                      GTK_SIGNAL_FUNC (on_moduleText_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textDict), "selection_notify_event",
                      GTK_SIGNAL_FUNC (on_moduleText_selection_notify_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textDict), "selection_get",
                      GTK_SIGNAL_FUNC (on_moduleText_selection_notify_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (textDict), "selection_received",
                      GTK_SIGNAL_FUNC (on_moduleText_selection_received),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnKeyPrev), "clicked",
                      GTK_SIGNAL_FUNC (on_btnKeyPrev_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (dictionarySearchText), "changed",
                      GTK_SIGNAL_FUNC (on_dictionarySearchText_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnKeyNext), "clicked",
                      GTK_SIGNAL_FUNC (on_btnKeyNext_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (list1), "select_row",
                      GTK_SIGNAL_FUNC (on_list1_select_row),
                      NULL);

  gtk_widget_grab_focus (mainwindow);
  return mainwindow;
}

static GnomeUIInfo menuInt1_uiinfo[] =
{
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

GtkWidget*
create_menuInt1 (void)
{
  GtkWidget *menuInt1;

  menuInt1 = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (menuInt1), "menuInt1", menuInt1);
  gnome_app_fill_menu (GTK_MENU_SHELL (menuInt1), menuInt1_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_ref (menuInt1_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (menuInt1), "copy1",
                            menuInt1_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menuInt1_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (menuInt1), "separator5",
                            menuInt1_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  return menuInt1;
}

static GnomeUIInfo menuInt2_uiinfo[] =
{
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy2_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

GtkWidget*
create_menuInt2 (void)
{
  GtkWidget *menuInt2;

  menuInt2 = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (menuInt2), "menuInt2", menuInt2);
  gnome_app_fill_menu (GTK_MENU_SHELL (menuInt2), menuInt2_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_ref (menuInt2_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (menuInt2), "copy2",
                            menuInt2_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menuInt2_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (menuInt2), "separator6",
                            menuInt2_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  return menuInt2;
}

static GnomeUIInfo menuInt3_uiinfo[] =
{
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy3_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_END
};

GtkWidget*
create_menuInt3 (void)
{
  GtkWidget *menuInt3;

  menuInt3 = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (menuInt3), "menuInt3", menuInt3);
  gnome_app_fill_menu (GTK_MENU_SHELL (menuInt3), menuInt3_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_ref (menuInt3_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (menuInt3), "copy3",
                            menuInt3_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (menuInt3_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (menuInt3), "separator7",
                            menuInt3_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  return menuInt3;
}

static GnomeUIInfo edit2_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_CUT_ITEM (on_cut1_activate, NULL),
  GNOMEUIINFO_MENU_COPY_ITEM (on_copy4_activate, NULL),
  GNOMEUIINFO_MENU_PASTE_ITEM (on_paste1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo pmEditnote_uiinfo[] =
{
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EDIT_TREE (edit2_menu_uiinfo),
  GNOMEUIINFO_END
};

GtkWidget*
create_pmEditnote (void)
{
  GtkWidget *pmEditnote;

  pmEditnote = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (pmEditnote), "pmEditnote", pmEditnote);
  gnome_app_fill_menu (GTK_MENU_SHELL (pmEditnote), pmEditnote_uiinfo,
                       NULL, FALSE, 0);

  gtk_widget_ref (pmEditnote_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (pmEditnote), "separator13",
                            pmEditnote_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (pmEditnote_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (pmEditnote), "edit2",
                            pmEditnote_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit2_menu_uiinfo[0].widget);
  gtk_object_set_data_full (GTK_OBJECT (pmEditnote), "cut1",
                            edit2_menu_uiinfo[0].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit2_menu_uiinfo[1].widget);
  gtk_object_set_data_full (GTK_OBJECT (pmEditnote), "copy4",
                            edit2_menu_uiinfo[1].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  gtk_widget_ref (edit2_menu_uiinfo[2].widget);
  gtk_object_set_data_full (GTK_OBJECT (pmEditnote), "paste1",
                            edit2_menu_uiinfo[2].widget,
                            (GtkDestroyNotify) gtk_widget_unref);

  return pmEditnote;
}

