/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_menu1 (void);
GtkWidget* create_mainwindow (void);
GtkWidget* create_menuInt1 (void);
GtkWidget* create_menuInt2 (void);
GtkWidget* create_menuInt3 (void);
GtkWidget* create_pmEditnote (void);
