/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fileselection1 (void);
GtkWidget* create_fileselectionSave (void);
GtkWidget* create_menu1 (void);
GtkWidget* create_mainwindow (void);
GtkWidget* create_propertybox1 (void);
GtkWidget* create_about2 (void);
GtkWidget* create_menuInt1 (void);
GtkWidget* create_menuInt2 (void);
GtkWidget* create_menuInt3 (void);
GtkWidget* create_dlgSearch (void);
GtkWidget* create_wdwEditBookmarks (void);
GtkWidget* create_dlgAboutSword (void);
GtkWidget* create_pmEditnote (void);
