#!/usr/bin/env python
# encoding: utf8

lib = bld.new_task_gen(
    features='cxx cc', # C++ with g++ and C with gcc
    includes='. ../.. ../../src %s' % bld.env['GECKO_INCLUDE'], # ../../ for config.h
    target='gecko',
    #uselib='GLIB GNOMEUI SWORD GTKMOZEMBED GTKMOZEMBED_UNSTABLE UPRINT',
    #uselib_local='backend', # needs libbackend.a
    uselib= bld.env['ALL_LIBS'],
)

lib.find_sources_in_dirs('.')

