#!/bin/sh
#
# idiotic Win32 use of pathname backward slashes causes no end of grief.
# aggressively convert all sequences of 2+ backslashes to a single forward slash.
# use this after "./waf configure" to make the world all sweetness and light.
# keep backups of the original files as written by waf.
# to keep the resulting diff small, we deliberately assert ^M in the result.
#
for i in build/default/config.h build/c4che/default.cache.py ; do
	echo '  =>' fixing backslashes in $i
	sed -i~ -e 's;\\\\\+;/;g' -e 's/$/\r/' $i
done
