#!/usr/bin/env python
# encoding: utf8

def build(bld):

    lib = bld.new_task_gen(
        features='cxx cc',
        includes='. ../.. ../../src %s' % bld.env['GECKO_INCLUDE'], # ../../ for config.h
        target='main',
        uselib='GLIB GTK GNOMEUI SWORD GTKMOZEMBED GTKMOZEMBED_UNSTABLE GECKONSS GECKONSPR GTKHTML UPRINT MAGICK',
        #uselib_local='backend gecko editor',
    )

    lib.find_sources_in_dirs('.')

