#! /usr/bin/env python

import Utils
import shutil

import Task
from TaskGen import feature
from Tools.ccroot import get_target_name

env = bld.env
sub = Utils.subst_vars

defines = sub('''
PREFIX="${PREFIX}"
SYSCONFDIR="${SYSCONFDIR}"
DATADIR="${DATAROOTDIR}"
LIBDIR="${LIBDIR}"
SHARE_DIR="${DATAROOTDIR}/${PACKAGE}"
''', env)

obj = bld.new_task_gen(
    features = 'cxx cc cprogram',
    includes = bld.env['DBUS'],
    defines = defines,
    target = 'xiphos-nav',
    uselib = bld.env['ALL_LIBS'],
    install_path = '${BINDIR}',
    strip = bld.env['TO_STRIP']
    )

obj.includes.append('.')
obj.source='''
xiphos-nav.c
'''

obj.add_dbus_file('ipc-interface.xml', 'ipc_object', 'glib-client')
obj.add_marshal_file('marshal.list', 'ipc_marshal')
