#!/usr/bin/env python

def build(bld):

    bld.install_files('${PACKAGE_DATA_DIR}', '*.png')
    bld.install_files('${PACKAGE_DATA_DIR}', '*.glade')
    bld.install_files('${PACKAGE_DATA_DIR}', """
        languages
        editor_studypad.xml
        editor_note.xml
        editor_link_dialog.xml
    """)
