#! /usr/bin/env python3
# encoding: utf-8

bld.install_files('${PACKAGE_DATA_DIR}', '*.png')
bld.install_files('${PACKAGE_DATA_DIR}', '*.glade')
bld.install_files('${PACKAGE_DATA_DIR}', '*.gtkbuilder')
bld.install_files('${PACKAGE_DATA_DIR}', '*.ui')
bld.install_files('${PACKAGE_DATA_DIR}', """
languages
editor_studypad.xml
editor_note.xml
""")
