#!/usr/bin/env python
# encoding: utf8

import Utils

def build(bld):

    env = bld.env
    sub = Utils.subst_vars
    
    # GTK
    #gtk = 'LIBGTK_X11_2_0'
    #if not env['HAVE_LIBGTK_X11_2_0']:
        #gtk = 'LIBGTK_WIN32_2_0'

    #gtk += ' %s' % 'GLIB GMODULEEXP'
    
    # use GECKO as html engine
    objects = 'backend editor main'
    if not bld.env['ENABLE_GTKHTML']:
        objects += ' %s' % 'gecko'

    # GTKHTML
    gtkhtml = 'GTKHTML'
    if env['HAVE_GTKHTML_EDITOR']:
        gtkhtml += ' %s' % 'GTKHTML_EDITOR'

    # GECKO
    gecko = 'GTKMOZEMBED'
    if env['HAVE_GTKMOZEMBED_UNSTABLE']:
        gecko += ' %s' % 'GTKMOZEMBED_UNSTABLE'

    # on WIN32 compile Xiphos icon into executable
    winresource = ''
    staticlib = []
    if env['IS_WIN32']:
        winresource = '../../win32/res/res.rc'
        staticlib = 'sword'.split()

    # DATADIR direct in config.h - conflict in win32 (mingw)
    defines = sub('''
        PREFIX="${PREFIX}"
        SYSCONFDIR="${SYSCONFDIR}"
        DATADIR="${DATAROOTDIR}"
        LIBDIR="${LIBDIR}"
        SHARE_DIR="${DATAROOTDIR}/${PACKAGE}"
    ''', env)
        
        
    lib = bld.new_task_gen(
        features = 'cxx cc cprogram',
        includes = '. ../.. ../../src ../../src/editor %s' % bld.env['GECKO_INCLUDE'], # ../../ for config.h
        defines = defines, 
        source = '%s' % winresource, 
        target = 'xiphos',
        uselib = 'GNOMEUI GECKONSPR MAGICK GECKONSS GTK GLADE GLIB GMODULEEXP UPRINT SWORD  %s %s' % (gtkhtml, gecko),
        staticlib = staticlib, # like cflag -lsword
        add_objects = objects, # used instead of libbackend.a, libgecko.a, libeditor.a, libmain.a
        install_path= '${BINDIR}',
    )

    lib.find_sources_in_dirs('.')

    # notification about project name change
    if not env['IS_WIN32']:
        is_executable = 0755
        bld.install_files('${BINDIR}', 'gnomesword2', chmod=is_executable)

